# Utiliser l'image officielle Apache avec PHP intégré
FROM php:apache

# Copier notre fichier index.php dans le dossier web Apache
COPY index.php /var/www/html/

# Exposer le port 80 pour l'accès via le navigateur
EXPOSE 80
