version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: morpion_game
    ports:
      - "8080:80"
    volumes:
      - game-results:/usr/share/nginx/html
    restart: always

volumes:
  game-results:
    driver: local
