version: '3.8'

services:
  web:
    build: .
    container_name: morpion_game
    ports:
      - "8080:80"
    volumes:
      - game-results:/var/www/html
    restart: always

volumes:
  game-results:
    driver: local
